openapi: 3.0.3
info:
  title: Meta-Spiegel Diagnose API
  description: API für interaktiven Fragen-Dialog basierend auf dem Meta-Spiegel-Modell zur Veränderungsfitness.
  version: 1.0.0

servers:
  - url: https://metaspiegel.vercel.app/api
    description: Produktionsserver (API-Route)

paths:
  /question:
    get:
      operationId: getQuestion
      summary: Aktuelle Frage holen
      responses:
        "200":
          description: Nächste Frage oder Abschlussinfo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionResponse"

  /answer:
    post:
      operationId: postAnswer
      summary: Antwort auf aktuelle Frage senden
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnswerRequest"
      responses:
        "200":
          description: Nächste Frage oder Abschlussinfo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnswerResponse"

  /summary:
    get:
      operationId: getSummary
      summary: Zusammenfassung ausgeben
      responses:
        "200":
          description: Zusammenfassung der Antworten
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SummaryResponse"

components:
  schemas:
    QuestionResponse:
      type: object
      properties:
        done:
          type: boolean
          description: Gibt an, ob der Fragebogen beendet ist
        question:
          type: string
          nullable: true
          description: Die aktuelle Frage (wenn nicht done)
      required:
        - done

    AnswerRequest:
      type: object
      properties:
        answer:
          type: string
          example: "Ja"
      required:
        - answer

    AnswerResponse:
      type: object
      properties:
        done:
          type: boolean
          description: Gibt an, ob der Fragebogen beendet ist
        nextQuestion:
          type: string
          nullable: true
          description: Die nächste Frage (wenn nicht done)
      required:
        - done

    SummaryResponse:
      type: object
      properties:
        summary:
          type: string
          description: Textuelle Zusammenfassung der bisherigen Antworten
      required:
        - summary
